import type { Metadata } from 'next';
import { ReactQueryProvider } from '@/components/providers/react-query-provider';
import { AuthProvider } from '@/components/providers/auth-provider';
import { AuthHeader } from '@/components/auth/auth-header';
import { Toaster } from 'sonner';
import React from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <AuthProvider>
            <div className="min-h-screen bg-background">
              <header className="border-b border-border bg-card">
                <div className="container mx-auto flex h-16 items-center justify-between px-4">
                  <div className="flex items-center space-x-4">
                    <h1 className="text-xl font-semibold">Mavericks Claims</h1>
                  </div>
                  <AuthHeader />
                </div>
              </header>
              <main>{children}</main>
            </div>
            <Toaster
              position="top-right"
              duration={5000}
              closeButton
              richColors
            />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
