import { describe, it, expect, beforeEach } from 'vitest';
import { EmailTemplateService } from '../email-template.service';
import { ClaimEntity } from 'src/modules/claims/entities/claim.entity';
import { AttachmentEntity } from 'src/modules/claims/entities/attachment.entity';
import { UserEntity } from 'src/modules/user/entities/user.entity';
import { ClaimCategory } from 'src/modules/claims/enums/claim-category.enum';
import { ClaimStatus } from 'src/modules/claims/enums/claim-status.enum';
import { AttachmentStatus } from 'src/modules/claims/enums/attachment-status.enum';

describe('EmailTemplateService', () => {
  let emailTemplateService: EmailTemplateService;
  let mockUser: UserEntity;
  let mockClaim: ClaimEntity;
  let mockAttachments: AttachmentEntity[];

  beforeEach(() => {
    emailTemplateService = new EmailTemplateService();

    // Mock UserEntity
    mockUser = {
      id: 'user-123',
      email: 'test.user@mavericks-consulting.com',
      name: 'John Doe',
      googleId: 'google-123',
      picture: 'https://example.com/photo.jpg',
      createdAt: new Date('2025-01-01T00:00:00Z'),
      updatedAt: new Date('2025-01-01T00:00:00Z'),
    } as UserEntity;

    // Mock ClaimEntity
    mockClaim = {
      id: 'claim-123',
      userId: 'user-123',
      category: ClaimCategory.TELCO,
      claimName: 'Monthly Phone Bill',
      month: 9,
      year: 2025,
      totalAmount: 125.5,
      status: ClaimStatus.DRAFT,
      submissionDate: null,
      createdAt: new Date('2025-09-01T00:00:00Z'),
      updatedAt: new Date('2025-09-01T00:00:00Z'),
    } as ClaimEntity;

    // Mock AttachmentEntity array
    mockAttachments = [
      {
        id: 'attachment-1',
        claimId: 'claim-123',
        originalFilename: 'receipt.pdf',
        storedFilename: 'receipt_stored.pdf',
        googleDriveFileId: 'drive-file-1',
        googleDriveUrl: 'https://drive.google.com/file/d/drive-file-1/view',
        fileSize: 102400,
        mimeType: 'application/pdf',
        status: AttachmentStatus.UPLOADED,
        createdAt: new Date('2025-09-01T00:00:00Z'),
        updatedAt: new Date('2025-09-01T00:00:00Z'),
      } as AttachmentEntity,
      {
        id: 'attachment-2',
        claimId: 'claim-123',
        originalFilename: 'invoice.jpg',
        storedFilename: 'invoice_stored.jpg',
        googleDriveFileId: 'drive-file-2',
        googleDriveUrl: 'https://drive.google.com/file/d/drive-file-2/view',
        fileSize: 204800,
        mimeType: 'image/jpeg',
        status: AttachmentStatus.UPLOADED,
        createdAt: new Date('2025-09-01T00:00:00Z'),
        updatedAt: new Date('2025-09-01T00:00:00Z'),
      } as AttachmentEntity,
    ];
  });

  describe('generateClaimEmail', () => {
    describe('Requirements 2.1, 2.4, 2.5, 2.6 - Template structure and content', () => {
      it('should generate complete HTML email with all required elements', () => {
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          mockAttachments,
        );

        // Verify HTML structure
        expect(html).toContain('<!DOCTYPE html>');
        expect(html).toContain('<html lang="en">');
        expect(html).toContain('<meta charset="UTF-8">');
        expect(html).toContain('<title>Claim Submission</title>');

        // Verify header
        expect(html).toContain('<h1>New Claim Submission</h1>');

        // Verify claim details section
        expect(html).toContain('Employee:');
        expect(html).toContain('John Doe');
        expect(html).toContain('Email:');
        expect(html).toContain('test.user@mavericks-consulting.com');
        expect(html).toContain('Category:');
        expect(html).toContain('Telecommunications');
        expect(html).toContain('Claim Name:');
        expect(html).toContain('Monthly Phone Bill');
        expect(html).toContain('Period:');
        expect(html).toContain('September 2025');
        expect(html).toContain('Total Amount:');
        expect(html).toContain('$125.50');
        expect(html).toContain('Submission Date:');

        // Verify attachments section
        expect(html).toContain('📎 Attachments (2)');
        expect(html).toContain('receipt.pdf');
        expect(html).toContain('invoice.jpg');
        expect(html).toContain(
          'https://drive.google.com/file/d/drive-file-1/view',
        );
        expect(html).toContain(
          'https://drive.google.com/file/d/drive-file-2/view',
        );

        // Verify footer
        expect(html).toContain(
          'This claim submission was automatically generated by the Mavericks Claim Submission System.',
        );
      });

      it('should handle missing optional claimName gracefully', () => {
        const claimWithoutName = { ...mockClaim, claimName: null };
        const html = emailTemplateService.generateClaimEmail(
          claimWithoutName,
          mockUser,
          mockAttachments,
        );

        // Should not contain claim name section
        expect(html).not.toContain('Claim Name:');
        expect(html).not.toContain('Monthly Phone Bill');

        // But should still contain other required elements
        expect(html).toContain('Employee:');
        expect(html).toContain('Category:');
        expect(html).toContain('Period:');
      });

      it('should handle empty attachments array', () => {
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          [],
        );

        expect(html).toContain('📎 Attachments (0)');
        expect(html).toContain('No attachments included with this claim.');
        expect(html).not.toContain('<ul class="attachment-list">');
      });

      it('should handle attachments without googleDriveUrl', () => {
        const attachmentWithoutUrl = {
          ...mockAttachments[0],
          googleDriveUrl: null,
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          [attachmentWithoutUrl],
        );

        expect(html).toContain('receipt.pdf');
        expect(html).toContain('(URL not available)');
        expect(html).not.toContain('href=');
      });

      it('should format different claim categories correctly', () => {
        const categories = [
          { enum: ClaimCategory.FITNESS, expected: 'Fitness & Wellness' },
          { enum: ClaimCategory.DENTAL, expected: 'Dental' },
          { enum: ClaimCategory.COMPANY_EVENT, expected: 'Company Event' },
          { enum: ClaimCategory.OTHERS, expected: 'Others' },
        ];

        categories.forEach(({ enum: category, expected }) => {
          const claimWithCategory = { ...mockClaim, category };
          const html = emailTemplateService.generateClaimEmail(
            claimWithCategory,
            mockUser,
            [],
          );
          expect(html).toContain(expected);
        });
      });

      it('should format currency amounts correctly', () => {
        const amounts = [
          { amount: 100, expected: '$100.00' },
          { amount: 1000.5, expected: '$1,000.50' },
          { amount: 0.99, expected: '$0.99' },
          { amount: 12345.67, expected: '$12,345.67' },
        ];

        amounts.forEach(({ amount, expected }) => {
          const claimWithAmount = { ...mockClaim, totalAmount: amount };
          const html = emailTemplateService.generateClaimEmail(
            claimWithAmount,
            mockUser,
            [],
          );
          expect(html).toContain(expected);
        });
      });

      it('should format month/year periods correctly', () => {
        const periods = [
          { month: 1, year: 2025, expected: 'January 2025' },
          { month: 6, year: 2024, expected: 'June 2024' },
          { month: 12, year: 2025, expected: 'December 2025' },
        ];

        periods.forEach(({ month, year, expected }) => {
          const claimWithPeriod = { ...mockClaim, month, year };
          const html = emailTemplateService.generateClaimEmail(
            claimWithPeriod,
            mockUser,
            [],
          );
          expect(html).toContain(expected);
        });
      });
    });

    describe('Requirement 2.7 - XSS Prevention', () => {
      it('should escape malicious HTML in user name', () => {
        const maliciousUser = {
          ...mockUser,
          name: '<script>alert("XSS")</script>John<img src=x onerror=alert(1)>',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          maliciousUser,
          [],
        );

        // Should escape HTML characters
        expect(html).not.toContain('<script>');
        expect(html).not.toContain('<img');
        expect(html).toContain('&lt;script&gt;');
        expect(html).toContain('&lt;img');
        expect(html).toContain('&quot;');
      });

      it('should escape malicious HTML in email address', () => {
        const maliciousUser = {
          ...mockUser,
          email: 'test@example.com<script>alert("XSS")</script>',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          maliciousUser,
          [],
        );

        expect(html).not.toContain('<script>');
        expect(html).toContain('&lt;script&gt;');
      });

      it('should escape malicious HTML in claim name', () => {
        const maliciousClaim = {
          ...mockClaim,
          claimName: '<img src=x onerror=alert("XSS")>Evil Claim</img>',
        };
        const html = emailTemplateService.generateClaimEmail(
          maliciousClaim,
          mockUser,
          [],
        );

        expect(html).not.toContain('<img');
        expect(html).not.toContain('onerror=alert("XSS")');
        expect(html).toContain('&lt;img');
        expect(html).toContain('Evil Claim');
        expect(html).toContain('&lt;img');
        expect(html).toContain('Evil Claim');
      });

      it('should escape malicious HTML in attachment filenames', () => {
        const maliciousAttachment = {
          ...mockAttachments[0],
          originalFilename: '<script>alert("XSS")</script>malicious.pdf',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          [maliciousAttachment],
        );

        expect(html).not.toContain('<script>');
        expect(html).toContain('&lt;script&gt;');
        expect(html).toContain('malicious.pdf');
      });

      it('should escape malicious HTML in Google Drive URLs', () => {
        const maliciousAttachment = {
          ...mockAttachments[0],
          googleDriveUrl:
            'https://drive.google.com/file/d/abc"><script>alert("XSS")</script>',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          [maliciousAttachment],
        );

        expect(html).not.toContain('"><script>');
        expect(html).toContain('&quot;&gt;&lt;script&gt;');
      });

      it('should handle XSS attempts with various HTML entities', () => {
        const maliciousUser = {
          ...mockUser,
          name: '&lt;script&gt;alert("already encoded")&lt;/script&gt;Test',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          maliciousUser,
          [],
        );

        // Should double-escape already encoded entities
        expect(html).toContain('&amp;lt;script&amp;gt;');
        expect(html).toContain('Test');
      });

      it('should escape quotes and apostrophes to prevent attribute injection', () => {
        const maliciousUser = {
          ...mockUser,
          name: 'Test" onmouseover="alert(\'XSS\')" name="evil',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          maliciousUser,
          [],
        );

        expect(html).not.toContain('onmouseover=alert');
        expect(html).toContain('&quot;');
        expect(html).toContain('&#39;');
      });

      it('should handle null and undefined values safely', () => {
        const userWithNullName = {
          ...mockUser,
          name: null as unknown as string,
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          userWithNullName,
          [],
        );

        // Should not throw error and should handle gracefully
        expect(html).toContain('Employee:');
        expect(html).toContain('<span class="detail-value"></span>');
      });
    });

    describe('HTML structure and CSS', () => {
      it('should include responsive CSS styles', () => {
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          mockAttachments,
        );

        expect(html).toContain('@media (max-width: 600px)');
        expect(html).toContain('flex-direction: column');
        expect(html).toContain('font-family:');
        expect(html).toContain('background-color:');
      });

      it('should include proper accessibility attributes', () => {
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          mockAttachments,
        );

        expect(html).toContain('target="_blank"');
        expect(html).toContain('rel="noopener noreferrer"');
        expect(html).toContain('lang="en"');
      });

      it('should use semantic HTML structure', () => {
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          mockAttachments,
        );

        expect(html).toContain('<ul class="attachment-list">');
        expect(html).toContain('<li class="attachment-item">');
        expect(html).toContain('<div class="claim-details">');
        expect(html).toContain('<div class="header">');
        expect(html).toContain('<div class="footer">');
      });
    });

    describe('Edge cases and error handling', () => {
      it('should handle very long claim names', () => {
        const longName = 'A'.repeat(500);
        const claimWithLongName = { ...mockClaim, claimName: longName };
        const html = emailTemplateService.generateClaimEmail(
          claimWithLongName,
          mockUser,
          [],
        );

        expect(html).toContain(longName);
        expect(html).toContain('Claim Name:');
      });

      it('should handle special characters in filenames', () => {
        const specialAttachment = {
          ...mockAttachments[0],
          originalFilename: 'résumé & cover_letter (final).pdf',
        };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          [specialAttachment],
        );

        expect(html).toContain('résumé &amp; cover_letter (final).pdf');
      });

      it('should handle empty strings in optional fields', () => {
        const claimWithEmptyName = { ...mockClaim, claimName: '' };
        const html = emailTemplateService.generateClaimEmail(
          claimWithEmptyName,
          mockUser,
          [],
        );

        // Empty string should be treated as missing
        expect(html).not.toContain('Claim Name:');
      });

      it('should handle large attachment arrays', () => {
        const manyAttachments = Array.from({ length: 10 }, (_, i) => ({
          ...mockAttachments[0],
          id: `attachment-${i}`,
          originalFilename: `file-${i}.pdf`,
          googleDriveFileId: `drive-file-${i}`,
          googleDriveUrl: `https://drive.google.com/file/d/drive-file-${i}/view`,
        }));

        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          manyAttachments,
        );

        expect(html).toContain('📎 Attachments (10)');
        expect(html).toContain('file-0.pdf');
        expect(html).toContain('file-9.pdf');
      });
    });
  });

  describe('generateSubject', () => {
    describe('Requirement 2.2 - Subject format', () => {
      it('should generate correct subject format', () => {
        const subject = emailTemplateService.generateSubject(
          mockClaim,
          mockUser,
        );

        expect(subject).toBe(
          'Claim Submission - Telecommunications - John Doe - 09/2025',
        );
      });

      it('should pad single-digit months with zero', () => {
        const claimInJanuary = { ...mockClaim, month: 1 };
        const subject = emailTemplateService.generateSubject(
          claimInJanuary,
          mockUser,
        );

        expect(subject).toContain('01/2025');
      });

      it('should handle different categories in subject', () => {
        const categories = [
          { enum: ClaimCategory.FITNESS, expected: 'Fitness & Wellness' },
          { enum: ClaimCategory.DENTAL, expected: 'Dental' },
          { enum: ClaimCategory.COMPANY_LUNCH, expected: 'Company Lunch' },
        ];

        categories.forEach(({ enum: category, expected }) => {
          const claimWithCategory = { ...mockClaim, category };
          const subject = emailTemplateService.generateSubject(
            claimWithCategory,
            mockUser,
          );
          expect(subject).toContain(expected);
        });
      });

      it('should escape HTML in subject line', () => {
        const maliciousUser = {
          ...mockUser,
          name: '<script>alert("XSS")</script>John',
        };
        const subject = emailTemplateService.generateSubject(
          mockClaim,
          maliciousUser,
        );

        expect(subject).not.toContain('<script>');
        expect(subject).toContain('&lt;script&gt;');
        expect(subject).toContain('John');
      });

      it('should handle unknown categories gracefully', () => {
        const claimWithUnknownCategory = {
          ...mockClaim,
          category: 'unknown-category' as ClaimCategory,
        };
        const subject = emailTemplateService.generateSubject(
          claimWithUnknownCategory,
          mockUser,
        );

        expect(subject).toContain('Unknown Category');
      });

      it('should handle hyphenated categories', () => {
        const claimWithHyphenated = {
          ...mockClaim,
          category: 'skill-enhancement' as ClaimCategory,
        };
        const subject = emailTemplateService.generateSubject(
          claimWithHyphenated,
          mockUser,
        );

        expect(subject).toContain('Skill Enhancement');
      });
    });
  });

  describe('Private helper methods (tested through public methods)', () => {
    describe('HTML escaping', () => {
      it('should escape all dangerous HTML characters', () => {
        const dangerousText = '&<>"\'';
        const testUser = { ...mockUser, name: dangerousText };
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          testUser,
          [],
        );

        expect(html).toContain('&amp;');
        expect(html).toContain('&lt;');
        expect(html).toContain('&gt;');
        expect(html).toContain('&quot;');
        expect(html).toContain('&#39;');
      });
    });

    describe('Category formatting', () => {
      it('should format known categories', () => {
        const knownCategories = [
          { input: ClaimCategory.TELCO, expected: 'Telecommunications' },
          { input: ClaimCategory.FITNESS, expected: 'Fitness & Wellness' },
          { input: ClaimCategory.DENTAL, expected: 'Dental' },
          { input: ClaimCategory.COMPANY_EVENT, expected: 'Company Event' },
          { input: ClaimCategory.COMPANY_LUNCH, expected: 'Company Lunch' },
          { input: ClaimCategory.COMPANY_DINNER, expected: 'Company Dinner' },
          { input: ClaimCategory.OTHERS, expected: 'Others' },
        ];

        knownCategories.forEach(({ input, expected }) => {
          const claimWithCategory = { ...mockClaim, category: input };
          const html = emailTemplateService.generateClaimEmail(
            claimWithCategory,
            mockUser,
            [],
          );
          expect(html).toContain(expected);
        });
      });

      it('should capitalize unknown categories', () => {
        const claimWithUnknown = {
          ...mockClaim,
          category: 'custom-category-name' as ClaimCategory,
        };
        const html = emailTemplateService.generateClaimEmail(
          claimWithUnknown,
          mockUser,
          [],
        );

        expect(html).toContain('Custom Category Name');
      });
    });

    describe('Date formatting', () => {
      it('should format dates in a readable format', () => {
        // The formatDate method is called internally for submission date
        const html = emailTemplateService.generateClaimEmail(
          mockClaim,
          mockUser,
          [],
        );

        // Check that the date appears in a readable format
        expect(html).toContain('Submission Date:');
        // The actual date format will depend on system locale, but should be readable
        expect(html).toMatch(/\d{1,2}:\d{2}/); // Should contain time
      });
    });
  });

  describe('Integration and consistency', () => {
    it('should generate consistent output for same input', () => {
      const html1 = emailTemplateService.generateClaimEmail(
        mockClaim,
        mockUser,
        mockAttachments,
      );
      const html2 = emailTemplateService.generateClaimEmail(
        mockClaim,
        mockUser,
        mockAttachments,
      );

      // Should be identical except for timestamp
      const html1WithoutTimestamp = html1.replace(/\d{1,2}:\d{2}.*/, 'TIME');
      const html2WithoutTimestamp = html2.replace(/\d{1,2}:\d{2}.*/, 'TIME');

      expect(html1WithoutTimestamp).toBe(html2WithoutTimestamp);
    });

    it('should generate complete, valid HTML document', () => {
      const html = emailTemplateService.generateClaimEmail(
        mockClaim,
        mockUser,
        mockAttachments,
      );

      // Basic HTML document structure validation
      expect(html.trim()).toMatch(/^<!DOCTYPE html>/);
      expect(html).toMatch(/<html[^>]*>[\s\S]*<\/html>$/);
      expect(html).toContain('<head>');
      expect(html).toContain('</head>');
      expect(html).toContain('<body>');
      expect(html).toContain('</body>');

      // Check for common HTML issues
      const openTags = (html.match(/<[^/][^>]*>/g) || []).length;
      const closeTags = (html.match(/<\/[^>]*>/g) || []).length;
      const selfClosingTags = (html.match(/<[^>]*\/>/g) || []).length;

      // Basic check that tags are roughly balanced (allowing for some CSS and complex structures)
      const tagDifference = Math.abs(openTags - selfClosingTags - closeTags);
      expect(tagDifference).toBeLessThan(10); // Allow some variance for CSS and complex HTML
    });
  });
});
